version: '3.9'

services:
  app:
    build: 
      context: .
    env_file:
      - .env.production
    ports:
      - "8099:8099"
    deploy:
      mode: replicated
      replicas: 1
    depends_on:
      - postgres

  postgres: 
    image: postgres:12-alpine
    ports:
      - "5435:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: media_library