version: '3.9'

services:
  app:
    build: 
      context: .
    env_file:
      - .env.production
    ports:
      - "8099:8099"
    volumes:
      - ./container/uploads:/uploads
    deploy:
      mode: replicated
      replicas: 1
    depends_on:
      postgres: 
        condition: service_healthy

  postgres: 
    image: postgres:12-alpine
    ports:
      - "5435:5432"
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: media_library
    volumes:
      - ./db-data/postgres/:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U root -d media_library"]
      interval: 10s
      timeout: 5s
      retries: 5
  
  migrator:
    image: migrate/migrate
    volumes:
      - ./internal/db/migration:/migrations
    command: [
      "-path", "/migrations", 
      "-database", "postgres://root:secret@postgres:5432/media_library?sslmode=disable",
      "up"
    ]
    depends_on:
      postgres: 
        condition: service_healthy